# get contents of event
GET http://127.0.0.1:8080/api/v1/event/2c3c0906-fbc1-46c3-9d66-582e5141a67f
Content-Type: application/json

###

# get contents of stream
GET http://127.0.0.1:8080/api/v1/streams/lol
Content-Type: application/json

###

# add an event to stream called lol
POST http://localhost:8080/api/v1/streams/lol
Content-Type: application/vnd+eventdb.event+json

{
  "event_type": "orderCreated",
  "event_data": {
    "issuer": "testing",
    "user": "bob"
  }
}

###

# add an event to stream lol with infomation in headers
POST http://localhost:8080/api/v1/streams/lol
Content-Type: application/json
X-Event-Type: orderCreated

{
  "issuer": "testing",
  "user": "bob"
}

###

# clear stream lol
POST http://localhost:8080/api/v1/streams/lol/clear

###

# get some metrics
GET http://localhost:8080/metrics